#pragma config(Sensor, in4,    lineTrackerCenter, sensorLineFollower)
#pragma config(Sensor, in5,    lineTrackerRight, sensorLineFollower)
#pragma config(Sensor, in6,    lineTrackerLeft, sensorLineFollower)
#pragma config(Sensor, dgtl2,  sonarSensor,    sensorSONAR_inch)
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port2,           claw,          tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port3,           arm,           tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void followLine(int threshold)
{
    //Loop until the sensor is 4-6 cm between the object
	while(SensorValue(sonarSensor) > 6)
    {
    	int temp = SensorValue(lineTrackerCenter);
        if(SensorValue(lineTrackerCenter) > threshold)
        {
            motor[left]  = 30;
            motor[right] = 30;
        }

        if(SensorValue(lineTrackerRight) > threshold)
        {
            motor[left]  = 0;
            motor[right] = 50;
        }

        if(SensorValue(lineTrackerLeft) > threshold)
        {
            motor[left]  = 50;
            motor[right] = 0;
        }
    }
     motor[left]  = 0;
     motor[right] = 0;
}

void clawOpen()
{
  motor[arm] = 30;
	//wait1Msec(1000);

	motor[claw] = 30;
	wait1Msec(1000);

	motor[arm] = 0;
	motor[claw] = 0;

}

void clawClose()
{
	motor[arm] = -30;
	wait1Msec(1000);

	motor[claw] = -30;
	wait1Msec(1000);

  motor[arm] = 30;
	wait1Msec(1000);
}

void findLine(int threshold)
{
	int floor = 2500;
	while (SensorValue(lineTrackerCenter) < floor)
	{
		int temp = SensorValue(lineTrackerCenter);
		motor[right] = 30;
		motor[left] = 30;
	}

	//motor[right] = 0;
	//motor[left] = 0;

}

void turnLeft()
{
	motor[left] = -50;
	motor[right] = 50;

	wait1Msec(1500);
}

task main()
{
	int threshold = 2000;

    //Open the claw
    clawOpen();

		//findLine(threshold);

		//Turn Left
		//turnLeft();

    //Follow the line
		//followLine(threshold);

    //Grab the Object
    //clawClose();



}
